// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pozjtjvldamemirsrowz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvemp0anZsZGFtZW1pcnNyb3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzU5MjksImV4cCI6MjA2NTE1MTkyOX0.hDQtbIf5vKNsYvQAUdvTLkjklAfknfvfbOPFXyE3vJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);